import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className='bg-slate-900 w-full h-screen text-center'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='w-full text-6xl font-bold text-green-300 py-12 text-center h-[95vh]'>
        <h1>NextJS & Tailwindcss Boilerplate</h1>
      </main>

      <footer className='text-white text-xs'>
        Powered by NextJS & Tailwindcss
      </footer>
    </div>
  )
}

export default Home
